### ISSUE TITLE
Absence de mesure

### ISSUE THREAD

**Issue by onlinux** [Scrat95220/DomoticzGazpar#1]
Merci pour ce nouveau script. 

Lorsque un relevé est manquant 'Absence de Données' le script plante.
ex: {'dateDebutReleve': '2021-11-16T06:00:00+01:00', 'dateFinReleve': '2021-11-17T06:00:00+01:00', 'journeeGaziere': '2021-11-16', 'indexDebut': None, 'indexFin': None, 'volumeBrutConsomme': None, 'energieConsomme': None, 'pcs': None, 'volumeConverti': None, 'pta': None, 'natureReleve': None, 'qualificationReleve': 'Absence de Données', 'status': None, 'coeffConversion': None, 'frequenceReleve': None, 'temperature': None}

Correction proposée:
<pre>for releve in j[str(numPce)]['releves']:
        print(releve)
        req_date = releve['journeeGaziere']
        conso = releve['energieConsomme']
        try :
            index = index + conso
        except TypeError:
            print(req_date, conso, index, "Invalid Entry")
            continue;
</pre>

Et ca marche.

**Comment by Sebastiii** [comment]
Marche impec, merci 👍

**Comment by Scrat95220** [comment]
> Merci pour ce nouveau script.
> 
> Lorsque un relevé est manquant 'Absence de Données' le script plante. ex: {'dateDebutReleve': '2021-11-16T06:00:00+01:00', 'dateFinReleve': '2021-11-17T06:00:00+01:00', 'journeeGaziere': '2021-11-16', 'indexDebut': None, 'indexFin': None, 'volumeBrutConsomme': None, 'energieConsomme': None, 'pcs': None, 'volumeConverti': None, 'pta': None, 'natureReleve': None, 'qualificationReleve': 'Absence de Données', 'status': None, 'coeffConversion': None, 'frequenceReleve': None, 'temperature': None}
> 
> Correction proposée:
> 
> for releve in j[str(numPce)]['releves']:
>         print(releve)
>         req_date = releve['journeeGaziere']
>         conso = releve['energieConsomme']
>         try :
>             index = index + conso
>         except TypeError:
>             print(req_date, conso, index, "Invalid Entry")
>             continue;
> Et ca marche.

C'est intégré. Je te remercie
