### ISSUE TITLE
Message d'erreur

### ISSUE THREAD

**Issue by dranreb38** [Scrat95220/DomoticzGazpar#10]
Salut,
je viens de mettre à jours avec la dernière version (05/12) , voici le message d'erreur:
```
2021-11-11 None 2428 Invalid Entry
2021-11-16 None 2602 Invalid Entry
```
Cela correspond à une absence de données.
![Screenshot_338](https://user-images.githubusercontent.com/16446911/144764824-c62bb096-2a5a-48e5-9494-ecef97564b32.png)
 
En réduisant le nombre de jours , c'est OK !

**Comment by Scrat95220** [comment]
Salut, en effet vu qu'il n'y a pas de données pour ces dates, aucune entrée n'est inséré pour ces dates et un message d'erreur est tracé.
Mais cela ne pose pas de soucis sur les dates qui ont bien des données, non?

**Comment by dranreb38** [comment]
Je ne sais pas encore, car l'import des données étaient déjà effectué, et pour l'instant je n'ai plus de mesures après le 30 Novembre... 
Est-ce que dans les log's ont peut voir les données importées ? (hors mis erreur)

**Comment by Scrat95220** [comment]
> Je ne sais pas encore, car l'import des données étaient déjà effectué, et pour l'instant je n'ai plus de mesures après le 30 Novembre... Est-ce que dans les log's ont peut voir les données importées ? (hors mis erreur)

Avec la dernière version en mettant les logs à "DEBUG", oui

**Comment by dranreb38** [comment]
Merci !
Bon toujours pas de nouvelles données .....

**Comment by biwizit** [comment]
@dranreb38 au cas où : as-tu vérifié sur ton compte Enedis dans la partie "Gérer l'accès de mes données" que tu as toujours "Collecte de la consommation horaire" activée ? De mon côté, j'avais fait ma demande de partage avec le plugin d'Emmanuel le 29 Novembre 2020 et au bout d'un an, ils ont coupé (alors que le mail reçu à l'époque donnait le droit pour 3 ans).
