### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by dltrainou** [Scrat95220/DomoticzGazpar#11]
bonjour et merci du taf, j'ai essayé de l'installer mais je tombe sur l'erreur : Login call - error status :REINPUT, qu'est ce a dire??
merci d'avance et bonne journée

**Comment by Scrat95220** [comment]
Bonjour,
Soit le login/password est incorrect, soit le catpcha est activé et il faut se logguer une fois sur le site en le cochant.
Vérifie aussi que dans le fichier de conf ton login et password ne contient pas les "

**Comment by dltrainou** [comment]
C’était bien les ", merci encore et bonne AM

**Comment by Scrat95220** [comment]
Parfait tant mieux, bon AM
