### ISSUE TITLE
Login call - error status :REINPUT

### ISSUE THREAD

**Issue by Ossetard** [Scrat95220/DomoticzGazpar#12]
Hello, 
Merci pour ce script. Pour ma part quand je le lance j'ai le message 
Login call - error status :REINPUT

Pourtant quand je me connecte à la page web j'arrive bien à me connecter.

**Comment by pbda** [comment]
Voir Issue #11

**Comment by Ossetard** [comment]
En fait entre temps j'ai trouvé... mode boulet... désolé.
