### ISSUE TITLE
Invalid Entry

### ISSUE THREAD

**Issue by djs45** [Scrat95220/DomoticzGazpar#13]
Hello
I'm testing your plugin and It Work !
I'm happy. I've juste one error :
"None 6990 Invalid Entry"

Do you know why ?

Many thanks
Sebastien

**Comment by Scrat95220** [comment]
Hello,
Try to switch the log in DEBUG mode and verifiy if some data are missing for some dates

**Comment by Scrat95220** [comment]
> Hello I'm testing your plugin and It Work ! I'm happy. I've juste one error : "None 6990 Invalid Entry"
> 
> Do you know why ?
> 
> Many thanks Sebastien

Can i close the issue ?
