### ISSUE TITLE
Commande à rajouter dans crontab, valeur du "Last seen"

### ISSUE THREAD

**Issue by biwizit** [Scrat95220/DomoticzGazpar#15]
Bonjour, 

Dans votre page d'accueil du plugin sur Github, pour crontab, vous dites qu'il faut rajouter par exemple : 
30 7,17 * * * /home/pi/domoticz/DomoticzGazpar/python3 gazpar.py

Ne serait-ce pas : 
30 7,17 * * * python3 /home/pi/domoticz/DomoticzGazpar/gazpar.py

Et contrairement à avant, on ne retrouve plus la bonne heure de mise à jour des valeurs dans Domoticz pour le device associé (la partie "Last seen") ? Elle correspond plutôt à l'ajout du device. Est-ce dû au fait qu'il s'agisse d'un Managed counter ? Ou autre ? C'est bien pratique de savoir qu'à 16h45, la dernière mise à jour est toujours celle de 7h30 et que ça ne sert à rien d'aller voir plus loin si on a déjà jeté un coup d'œil à midi. 

Quoi qu'il en soit, merci pour la refonte de Domoticz Gazpar !

**Comment by biwizit** [comment]
J'ai créé un pull request pour la petite modif dans le README.
Toujours intéressé par la partie Last seen.
Merci !

**Comment by Scrat95220** [comment]
Merged. Merci
