### ISSUE TITLE
Passage en HTTPS

### ISSUE THREAD

**Issue by LD40** [Scrat95220/DomoticzGazpar#18]
Le script actuel impose que domoticz accepte le HTTP.
Si seul le HTTPS est supporté, il faut modifier le code.
Proposition : supprimer le http:// en dur dans le code et le reporter dans le paramètre serveur du fichier de config. cela permettrait de gérer HTTP ou HTTPS

P.S. : merci pour la réécriture complète du plugin en Python.

**Comment by Scrat95220** [comment]
Merged. Merci
