### ISSUE TITLE
nodejs ?

### ISSUE THREAD

**Issue by pbda** [Scrat95220/DomoticzGazpar#2]
Merci pour ce script très efficace. 2 remarques:

- je ne comprends pas bien la dépendance avec nodejs et npm
- il est possible facilement d'exécuter les requêtes SQL directement dans le script python avec quelque chose du genre:

import sqlite3
	conn = sqlite3.connect(Domoticz_DB)
	conn.executescript(sql)
	conn.commit()
	conn.close()

**Comment by onlinux** [comment]
No more nodejs required
