### ISSUE TITLE
erreur bizarre

### ISSUE THREAD

**Issue by dltrainou** [Scrat95220/DomoticzGazpar#22]
bonjour
j'ai essayé le nouveau plugin et j'ai une erreur au lancement
{'reason': 'unknown url type: localhost'}
le plugin precedent fonstionnait nickel?? le cfg n'a pas été changé!!
une idée?
merci d'avance

**Comment by LD40** [comment]
Bonjour,
Désormais il faut ajouter http:// ou https:// devant le nom du serveur dans HOSTNAME dans le fichier de configuration.
cf exemple dans le [README](https://github.com/Scrat95220/DomoticzGazpar#readme)

**Comment by dltrainou** [comment]
ok je modifie, merci et bonne journée
