### ISSUE TITLE
Plus de données

### ISSUE THREAD

**Issue by ebretteville** [Scrat95220/DomoticzGazpar#35]
Bonjour et tous d'abord merci pour ce plugin. Depuis qqsjours, plus de données. Lorsque j'éxécute:

`
pi@domoticz-tours:~/domoticz/plugins $ cd DomoticzGazpar/
pi@domoticz-tours:~/domoticz/plugins/DomoticzGazpar $ ll
total 68
-rwxr-xr-x 1 pi pi   888 févr. 20 22:36 CHANGELOG
-rwxr-xr-x 1 pi pi   434 févr. 20 22:36 _domoticz_gazpar.cfg
-rwxr-xr-x 1 pi pi   477 févr. 20 22:59 domoticz_gazpar.cfg
-rw-r--r-- 1 pi pi   195 mai    2 07:30 domoticz_gazpar.log
-rwxr-xr-x 1 pi pi 11484 févr. 20 22:36 [gazpar.py](https://gazpar.py/)
-rwxr-xr-x 1 pi pi 35141 févr. 20 22:36 LICENSE
-rwxr-xr-x 1 pi pi  1509 févr. 20 22:36 [README.md](https://readme.md/)
pi@domoticz-tours:~/domoticz/plugins/DomoticzGazpar $ more domoticz_gazpar.log
2022-05-02 16:41:10,919 logging in as [brettevillenormand@gmail.com](mailto:brettevillenormand@gmail.com)...
2022-05-02 16:41:11,673 logged in successfully!
2022-05-02 16:41:11,673 retrieving data...
2022-05-02 16:41:13,487 got data!
pi@domoticz-tours:~/domoticz/plugins/DomoticzGazpar $
`
Il semble que le plugin est trouvé des données mais rien dans domoticz. Les ids des devices sont bons.

Dernières donées le 25 avril

**Comment by Scrat95220** [comment]
Bonjour, as-tu toujours le soucis?
Si oui as-tu des erreurs dans le fichier de log?

**Comment by Scrat95220** [comment]
Je soupçonne un problème avec les DeviceID. Mets à jour le script et mets toi en mode debug comme ceci :
[SETTINGS]
LOG_LEVEL=DEBUG

J'ai rajouté des traces avec les Requêtes vers l'API domoticz et les Réponses de l'API.
En cas d'erreur lors de l'update du device tu auras : 
{
	"status" : "ERR",
}
Si le Device est correctement mis à jour tu auras :
{
	"status" : "OK",
	"title" : "Update Device"
}

**Comment by ebretteville** [comment]
Le pbm semble réglé, j'ai des status OK. Même devices, je ne sais pas ce qu'il c'est passé.

**Comment by ebretteville** [comment]
`status":null,`

Suite à crash de carte sd, que peut expliquer ce status?
