### ISSUE TITLE
Login call - error status :REINPUT

### ISSUE THREAD

**Issue by lolo-b** [Scrat95220/DomoticzGazpar#57]
Bonjour,

J'ai ré-installé DomoticzGazpar et téléchargé mes consos journalières dans un fichier xlsx.

Quand je lance gazpar.py, j'ai l'erreur suivante:

Login call - error status :REINPUT

{'code': 401, 'msg': 'Unauthorized', 'hdrs': <http.client.HTTPMessage object at 0x7fb00d5990>, 'fp': <http.client.HTTPResponse object at 0x7faff8b700>, 'file': <http.client.HTTPResponse object at 0x7faff8b700>, 'name': '<urllib response>', 'delete': False, '_closer': <tempfile._TemporaryFileCloser object at 0x7fb0435c50>, 'url': 'http://localhost:8080/json.htm?type=command&param=udevice&idx=48&svalue=1440%3B61000%3B2023-12-20'}

Si je met sur une page internet la commande:

http://192.168.1.80:8080/json.htm?type=command&param=udevice&idx=48&svalue=1440%3B61000%3B2023-12-20, je récupère bien l'information dans domoticz et un est le retour suivant sur la page internet de mon PC où j'ai tapé la commande:

{
	"status" : "OK",
	"title" : "Update Device"
}

L'adresse 192.168.1.80 correspond à mon serveur PI où tourne domoticz et le script (donc correspond au localhost.

Que dois-je faire pour récupérer automatique les informations du fichier excel?

**Comment by erwann2000** [comment]
Tu peux essayer de remplacer HOSTNAME=http://localhost par HOSTNAME=http://127.0.0.1 dans le fichier domoticz_gazpar.cfg

**Comment by lolo-b** [comment]
Cela a fonctionné en mettant l'adresse de mon serveur sans oublié ":8080" à la fin.
Merci
