### ISSUE TITLE
y a t il du nouveau sur cet outil, bien pratique ?

### ISSUE THREAD

**Issue by Phil353556** [Scrat95220/DomoticzGazpar#58]
Bonjour,

y a t il du nouveau sur cet outil, bien pratique ?

Merci

**Comment by Scrat95220** [comment]
J'ai fait un version qui screenscrape le site grdf, qui download la consommation et qui injecte les datas dans domoticz en m'inspirant de ce qui a été fait pour les données Veolia IDF.
Je la mettrais à dispo sous peu

**Comment by Scrat95220** [comment]
J'ai mis une version utilisant Selenium sur une branche "selenium":
https://github.com/Scrat95220/DomoticzGazpar/tree/selenium

**Comment by djs45** [comment]
Hello and thanks for your job.
I have this error in debug mode. Any idea ?

Start the browser                                                          [EE] Timeout value connect was <object object at 0x766f9e00>, but it must be an int, float or None.
Close Browser                                                              [OK]
Close Display                                                              [OK]
Ended with error                                                           [EE]

**Comment by ldrolez** [comment]
On dirait que le capcha a disparu?

**Comment by Scrat95220** [comment]
> On dirait que le capcha a disparu?

Oui et j'ai mis une version utilisant Selenium sur une branche "selenium":
https://github.com/Scrat95220/DomoticzGazpar/tree/selenium
