### ISSUE TITLE
Log file will grow indefinitely 

### ISSUE THREAD

**Issue by pbda** [Scrat95220/DomoticzGazpar#7]
As logging append to log file `domoticz_gazpar.log` it will grow indefinitely. Log file should  be destroyed at start or truncated.

**Comment by pbda** [comment]
Suggestion: il suffit d'ajouter `filemode='w'` à la ligne `logging.basicConfig(..)` pour que le fichier soit écrasé à chaque fois

**Comment by Scrat95220** [comment]
Corrected. Thanks
