### ISSUE TITLE
Login fail due to RECAPTCHA

### ISSUE THREAD

**Issue by jbremond** [Scrat95220/DomoticzGazpar#9]
Hello,

It seems that GRDF web site as put in place a google RECAPTCHA...
When launching the script, I get :
`Login call - error status :REINPUT`

Any way to workaround this ? Or am I alone to have this problem ?

I am using master (15db90abaacedfb85692625ee715d907113a3de3)

**Comment by Scrat95220** [comment]
Hello,
Try to reconnect directly on the GRDF website with the captcha validation. Normally after the script will work

**Comment by jbremond** [comment]
Ok. It is was I did, but from another computer (but same WAN IP).
I will try to do it from the server that run the script.
Will keep you inform.
Thanks

**Comment by jbremond** [comment]
I found the issue, this was not related to RECAPCHA :
`{"state":"REINPUT","error":"EMAIL_INVALID_FORMAT","actualLockoutDuration":0,"message":"login.error.formatmail","displayCaptcha":true}`
My email was surrounded with quote (") in the configuration file (was using domoticz_gaspar project before).
After the fix in my conf file, everything is OK now.
You can close the issue :-)

Thanks
